DROP TABLE APPS.TRNT_SEGMENT_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_SEGMENT_CONFIG
(
  APPLICATION_ID           NUMBER(10)           NOT NULL,
  COLUMN_NAME              VARCHAR2(30 BYTE)    NOT NULL,
  APPLICATION_COLUMN_NAME  VARCHAR2(30 BYTE)    NOT NULL,
  SEGMENT_NAME             VARCHAR2(30 BYTE)    NOT NULL,
  DISP_IN_REPORT           CHAR(1 BYTE),
  DISP_IN_QUERY            CHAR(1 BYTE),
  DISPLAY_ORDER            NUMBER,
  SEGMENT_DISP_NAME        VARCHAR2(30 BYTE),
  LEDGER_ID                VARCHAR2(30 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
