DROP TABLE APPS.TRNT_CONFIG_INCREMENTAL CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_CONFIG_INCREMENTAL
(
  CONFIG_ID          NUMBER,
  FISCAL_YEAR        NUMBER,
  PERIOD             VARCHAR2(50 BYTE),
  LAST_EXTRACT_DATE  DATE
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
