DROP TABLE APPS.TRNT_CONFIG_ADDITION_COL CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_CONFIG_ADDITION_COL
(
  CONFIG_ID       NUMBER,
  COLOUM_NAME     VARCHAR2(50 BYTE),
  COLOUM_DISPLAY  VARCHAR2(50 BYTE),
  DISPLAY_YN      CHAR(1 BYTE),
  TABLEALIAS      CHAR(3 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
