DROP TABLE APPS.TRNT_SEGMENT_SELECTION CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_SEGMENT_SELECTION
(
  CONFIG_ID        NUMBER(10)                   NOT NULL,
  SEGMENT_SLNO     VARCHAR2(50 BYTE)            NOT NULL,
  SEGMENT_DESC     VARCHAR2(50 BYTE),
  SEGMENT_NAME     VARCHAR2(50 BYTE),
  SEGMENT_LABEL    VARCHAR2(50 BYTE),
  SEGMENT_DISP     VARCHAR2(5 BYTE),
  RM_LEADZERO      VARCHAR2(100 BYTE),
  RM_SPECIAL_CHAR  VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
