DROP TABLE APPS.TRNT_CONFIG_SEGMENT_LIST CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_CONFIG_SEGMENT_LIST
(
  CONFIG_ID              NUMBER,
  SEGMENT_SET            VARCHAR2(1000 BYTE),
  CONCATENATED_SEGMENTS  VARCHAR2(1000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
