DROP TABLE APPS.TRNT_CONFIG_SEGMENT CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_CONFIG_SEGMENT
(
  CONFIG_ID         NUMBER,
  SEGMENT_SET_ID    VARCHAR2(50 BYTE),
  SEGMENT_SET_NAME  VARCHAR2(50 BYTE),
  SEGMENT1_FROM     VARCHAR2(30 BYTE),
  SEGMENT1_TO       VARCHAR2(30 BYTE),
  SEGMENT1_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT2_FROM     VARCHAR2(30 BYTE),
  SEGMENT2_TO       VARCHAR2(30 BYTE),
  SEGMENT2_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT3_FROM     VARCHAR2(30 BYTE),
  SEGMENT3_TO       VARCHAR2(30 BYTE),
  SEGMENT3_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT4_FROM     VARCHAR2(30 BYTE),
  SEGMENT4_TO       VARCHAR2(30 BYTE),
  SEGMENT4_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT5_FROM     VARCHAR2(30 BYTE),
  SEGMENT5_TO       VARCHAR2(30 BYTE),
  SEGMENT5_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT6_FROM     VARCHAR2(30 BYTE),
  SEGMENT6_TO       VARCHAR2(30 BYTE),
  SEGMENT6_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT7_FROM     VARCHAR2(30 BYTE),
  SEGMENT7_TO       VARCHAR2(30 BYTE),
  SEGMENT7_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT8_FROM     VARCHAR2(30 BYTE),
  SEGMENT8_TO       VARCHAR2(30 BYTE),
  SEGMENT8_EXCLUDE  VARCHAR2(100 BYTE),
  SEGMENT9_FROM     VARCHAR2(30 BYTE),
  SEGMENT9_TO       VARCHAR2(30 BYTE),
  SEGMENT9_EXCLUDE  VARCHAR2(100 BYTE),
  LEDGER            VARCHAR2(100 BYTE),
  ACTIVE            VARCHAR2(10 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
