DROP TABLE APPS.TRNT_CONFIG_TYPE CASCADE CONSTRAINTS;

CREATE TABLE APPS.TRNT_CONFIG_TYPE
(
  CONFIG_TYPE       VARCHAR2(20 BYTE),
  DESCRIPTION       VARCHAR2(200 BYTE),
  PROGRAM_NAME      VARCHAR2(200 BYTE),
  APPLICATION_CODE  VARCHAR2(200 BYTE),
  ACTIVE            VARCHAR2(1 BYTE),
  DISPLAY_ORDER     NUMBER(3),
  FILE_NAME_PREFIX  VARCHAR2(200 BYTE),
  DEFAULT_TYPE      VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
